/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testGradle;

public class Calculadora {
	public static int suma (int a, int b) {
		return a + b;
	}
	
	public static int resta(int a, int b) {
		return a - b;
	}
}
