/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testGradle;

import org.junit.Test;

import static org.junit.Assert.*;

public class CalculadoraTest {

	@Test
	public void testSuma() {
		int resultado = Calculadora.suma(2, 3);
		int esperado = 5;
		assertEquals(esperado,resultado);
	}
	
	@Test
	public void testResta() {
		int resultado = Calculadora.resta(3, 2);
		int esperado = 4;
		assertEquals(esperado,resultado);
	}

}